language: go

go:
  - 1.14.x

before_install:
  - go get -u golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

scripts:
  - make test
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
