language: go

go:
  - 1.14.x

jobs:
  include:
    - stage: test
      script: make test
    - stage: install
      script: go get -u github.com/mattn/goveralls
    - stage: coveralls
      script: $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci

stages:
  - test
  - name: install
    if: branch = edge
  - name: coveralls
    if: branch = edge
